// Forbid accidental stdout/stderr writes in the library portion of the TUI.
#![deny(clippy::print_stdout, clippy::print_stderr)]
#![deny(clippy::disallowed_methods)]

mod exit;

mod action_picker_prompt;
mod ansi_escape;
mod app_event;
mod app_event_sender;
mod app_server_render;
mod bottom_pane;
mod codex_config;
mod codex_home;
mod codex_system_paths;
mod color;
mod commentary_status;
mod custom_terminal;
mod diff_render;
mod exec_cell;
mod exec_command;
mod exec_human_output;
mod external_editor;
mod external_editor_integration;
mod file_search;
mod global_gitignore_prompt;
mod history_cell;
mod history_cell_potter;
mod human_time;
mod insert_history;
mod interrupted_project_prompt;
mod key_hint;
mod line_truncation;
mod live_wrap;
mod local_path;
mod markdown;
mod markdown_render;
mod markdown_stream;
mod mention_codec;
mod multi_agents;
mod path_utils;
mod potter_config;
mod potter_project_summary;
mod potter_tui;
mod projects_overlay;
mod prompt_history_store;
mod reasoning_status;
mod render;
mod resume_picker_prompt;
mod selection_list;
mod shimmer;
mod skills_discovery;
mod slash_command;
mod startup_banner;
mod startup_setup;
mod status_indicator_widget;
mod status_line;
mod streaming;
mod style;
mod terminal_cleanup;
mod terminal_palette;
mod text_formatting;
mod theme_picker;
mod token_format;
mod tui;
mod ui_colors;
mod ui_consts;
mod update_action;
mod update_prompt;
mod updates;
mod verbosity;
mod verbosity_picker;
mod verbosity_prompt;
mod version;
mod wrapping;
mod yolo_picker;

#[cfg(test)]
mod test_backend;

pub use bottom_pane::PromptFooterContext;
pub use exec_human_output::ExecHumanRenderer;
pub use exit::AppExitInfo;
pub use exit::ExitReason;
pub use global_gitignore_prompt::GlobalGitignorePromptOutcome;
pub use global_gitignore_prompt::run_global_gitignore_prompt;
pub use interrupted_project_prompt::InterruptedProjectAction;
pub use potter_tui::CodexPotterTui;
pub use potter_tui::ProjectsOverlayProviderChannels;
pub use potter_tui::ProjectsOverlayRequest;
pub use potter_tui::ProjectsOverlayResponse;
pub use potter_tui::RenderRoundParams;
pub use resume_picker_prompt::ResumePickerOutcome;
pub use update_action::UpdateAction;
pub use version::CODEX_POTTER_VERSION;

pub use markdown_render::render_markdown_text;
pub use potter_config::load_potter_tui_verbosity;
pub use potter_config::load_potter_yolo_enabled;
pub use potter_config::load_potter_yolo_enabled_from_path;
pub use startup_setup::StartupSetupStep;
pub use verbosity::Verbosity;
